services:

  nginx:
    container_name: nginx-master
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./src/conf.d/master/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - loadbalancer
  
  node1:
    container_name: node1
    image: nginx:alpine
    restart: always
    depends_on:
      - nginx
    ports:
      - "80"
    volumes:
      - ./src/conf.d/nodes/nginx.conf:/etc/nginx/nginx.conf
      - ./src/conf.d/nodes/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/nodes.d/node.1/:/usr/share/nginx/html
    networks:
      - loadbalancer

  node2:
    container_name: node2
    image: nginx:alpine
    restart: always
    depends_on:
      - nginx
    ports:
      - "80"
    volumes:
      - ./src/conf.d/nodes/nginx.conf:/etc/nginx/nginx.conf
      - ./src/conf.d/nodes/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/nodes.d/node.2/:/usr/share/nginx/html
    networks:
      - loadbalancer

  node3:
    container_name: node3
    image: nginx:alpine
    restart: always
    depends_on:
      - nginx
    ports:
      - "80"
    volumes:
      - ./src/conf.d/nodes/nginx.conf:/etc/nginx/nginx.conf
      - ./src/conf.d/nodes/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/nodes.d/node.3/:/usr/share/nginx/html
    networks:
      - loadbalancer

networks:
  loadbalancer:
      driver: bridge
